### ISSUE TITLE
How to enable the log in haihcviewer?

### ISSUE THREAD

**Issue by ojalaj** [dingusdk/haihcviewer#10] opened 2020-09-13 19:19 UTC
It says "false". I have IHC Controller HW 6.1 FW 2.7.220. Downloaded the new code version, copied under custom components, restarted HA and also emptied the browser history.

**Comment by dingusdk** [comment] 2020-09-13 19:56
Is your log empty if you look in the ihc service view application?
(Just guessing if that could be the cause - empty showing as "false")

**Comment by ojalaj** [comment] 2020-09-15 19:25
Hmm...I can't find anything related to logs in IHC ServiceView application nor in other IHC applications I have. Can't find any setting to turn logging on/off. Have you any further information?

**Comment by dingusdk** [comment] 2020-09-15 19:47
This is how it look in the danish version of the Service View application:

![image](https://user-images.githubusercontent.com/28299108/93257200-cf1d8a80-f79c-11ea-8444-3bc1150ffdd9.png)

The log area is the lower left part. (I have one line in the log about a low battery)

**Comment by ojalaj** [comment] 2020-09-15 20:01
Thanks. Actually by right-clicking the lower left window I can set logging options. It seems that I need to one by one select logging on/off with all inputs and outputs. I'll test with couple of them and see will I get data in haihcviewer. Do I need to restart HA in order to this have effect?

**Comment by dingusdk** [comment] 2020-09-15 20:07
You don't need to do that - this is just for have changes logged in this session of you service view - it is not something permanent stored in the controller. I guess this is for troubleshooting so you can monitor some specific in/outputs for changes. 

I have another idea. When getting the log from the controller you have to specify a language, and i have not made this configurable - it will always ask for English. I can see you are from Finland, so if your controller does not have English? that could be the issue. In the service view you can change language on the button in the upper right corner- too what languages you have. The Danish version also have English - so i assumed all would have English, but that may be wrong.

If you want to try it you can change line 109 in ___init__py:

 def get_user_log(self, language="en"):

Then change "en" to "fi"

You have to restart HA after you have made the change.

**Comment by dingusdk** [comment] 2020-09-15 20:08
That is the __init__.py file in custom_components/ihcviewer

**Comment by ojalaj** [comment] 2020-09-15 20:12
Yes, at least the controller originally was in Finnish, but in order have the latest FW for it, I needed to upgrade with English FW. But at least ServiceView and the texts are in Finnish. I'll give a try for above and let you know - thanks!

**Comment by ojalaj** [comment] 2020-09-15 20:18
I seem to have Finnish and English in IHC ServiceView, with Finnish selected.

**Comment by ojalaj** [comment] 2020-09-15 20:20
Hmm, it still gives "false" after applying the change to ___init__py  and restarting HA.

**Comment by dingusdk** [comment] 2020-09-15 21:30
I tried to empty my controller log, and then I also get "false.
Anyway the only thing i remember having seen in the log is battery warnings - that is also why i added it - because i have not found any other way see low battery levels.

I will make a change later so it will just be empty en not say "false"

**Comment by ojalaj** [comment] 2020-09-16 05:20
OK - great! I somehow expected that it would have the log data for all the state changes etc. But having the battery warning is great as well. Maybe you could change it to say "Empty" instead of "false" or being just empty.

**Comment by dingusdk** [comment] 2020-09-17 21:11
This fix is now included so i will close this issue

**Closed by dingusdk** 2020-09-17 21:11 UTC
