### ISSUE TITLE
Error loading IHC viewer

### ISSUE THREAD

**Issue by jhoejgaard** [dingusdk/haihcviewer#12] opened 2021-01-26 07:40 UTC
After a recent update to either HomeAssistant or IHC Viewer the IHC Viewer cannot perform initial load. I have not made any changes to my IHC installation. I get this error

```
Logger: aiohttp.server
Source: custom_components/ihcviewer/__init__.py:110
First occurred: 12:00:34 AM (2 occurrences)
Last logged: 8:35:47 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_response.py", line 620, in body
    self._body = body = payload.PAYLOAD_REGISTRY.get(body)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/payload.py", line 112, in get
    raise LookupError()
aiohttp.payload.LookupError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 118, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/config/custom_components/ihcviewer/__init__.py", line 110, in get
    return web.Response(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_response.py", line 595, in __init__
    self.body = body
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_response.py", line 622, in body
    raise ValueError("Unsupported body type %r" % type(body))
ValueError: Unsupported body type <class 'bool'>
```

**Comment by dingusdk** [comment] 2021-02-01 08:41
This is not something i can reproduce - what is your version of Home Assistant and the IHC Viewer?

The erroir is when IHC viewer tries to get the project from the controller, so you could also try to restart eveerything - the controller and Home Assistant.

**Comment by dingusdk** [comment] 2021-02-16 15:49
Since there has been no reponse on this for 14 days, and the new version is out, i will assume this is not a problem anymore and close the issue

**Closed by dingusdk** 2021-02-16 15:49 UTC
