### ISSUE TITLE
ruamel.yaml is no longer included as of 2022.7

### ISSUE THREAD

**Issue by davidolrik** [dingusdk/haihcviewer#17] opened 2022-07-07 08:38 UTC
The handling of YAML and JSON has changed a lot in 2022.7, and because of that ruamel.yaml is no longer included.

**Comment by dingusdk** [comment] 2022-07-09 18:24
ruamel.yaml has not been in HA for some time, but is included in the manifest for ihcviewer and should be installed. This has been working until version 2022.7.1 The problem is not within ihcviewer it it the ruamel.yaml package that fails to install. I run HA in docker on my dev computer with the ludeeus/devcontainer image - here there is not problem. On my "production" ha also running docker it will not load ruamel.yaml - the HA docker image is based on alpine. Installing musl-dev and gcc before ruamel.yaml will make it work on my computer. These 3 command in the docker container:

_apk add --no-cache musl-dev
apk add --no-cache gcc
pip install ruamel.yaml_

After a restart of home assistant ihcviewer is not working again.

I think the long term fix is to find another way to do yaml not using ruamel.yaml. I anyone know what to use as an alternative let me know - it must be a yaml library that can keep the original layout and comments.

**Comment by duddi** [comment] 2022-07-24 00:38
From my mainfest.json
  "requirements": [
    "ihcsdk==2.7.6",
    "ruamel.yaml==0.17.15" 

If you change the version to 0.17.15 it's work in HA 2022.7.6

**Comment by dingusdk** [comment] 2022-07-24 16:43
Look like going back to version 17.15 Will work. I have merged your PR and published a new release.

**Closed by dingusdk** 2022-07-24 16:43 UTC
